services:
  favorite_literature_works_database:
    container_name: works_db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "fav_lit_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "7000:5432"

  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: rabbit-mq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq