name: CI

on:
  push:
    branches: 
      - "develop"
  pull_request:
    branches: 
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.x'

      - name: Prepare NuGet Config
        run: |
          mkdir -p ~/.nuget/NuGet/
          cp ./NuGet.Config ~/.nuget/NuGet/NuGet.Config

      - name: Build
        run: dotnet build

  create_image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login -u ${{ secrets.CI_REGISTRY_USER }} ${{ secrets.CI_REGISTRY }} --password-stdin

      - name: Determine Container Version
        run: |
          if [ "${{ github.ref }}" != "refs/heads/main" ]; then
            CONTAINER_VERSION="rc"
          else
            CONTAINER_VERSION="release"
          fi
          echo "Container version: $CONTAINER_VERSION"

      - name: Build and Push Docker Image
        run: |
          CONTAINER_TAG=${{ secrets.CI_REGISTRY_IMAGE }}:${CONTAINER_VERSION}
          echo "Container tag: $CONTAINER_TAG"
          docker build -t $CONTAINER_TAG -t ${{ secrets.CI_REGISTRY_IMAGE }}:latest .
          docker push $CONTAINER_TAG
          docker push ${{ secrets.CI_REGISTRY_IMAGE }}:latest
        env:
          CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
          CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
          CI_REGISTRY: ${{ secrets.CI_REGISTRY }}
          CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
